[default_session]

[[session]]
name = "home"
path = "~"

[[session]]
name = "desktop"
path = "~/Desktop"
startup_command = "yazi"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"
